# Generated by Django 3.0.5 on 2020-05-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20200519_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='blog_sub',
        ),
    ]
