# Generated by Django 3.0.5 on 2020-05-19 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_remove_subscription_blog_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
