# Generated by Django 3.0.5 on 2020-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200414_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
